name: release-branch

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  branch-out:
    name: Create a github branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Bump main version
        run: make patch

      - name: Get the branch version
        id: get_branch
        run: |
          BRANCH=${GITHUB_REF/refs\/tags\//}
          if ${{github.event_name == 'workflow_dispatch'}}; then
            BRANCH=$(git describe --abbrev=0 --tags)
          fi
          echo ::set-output name=BRANCH::$(echo ${BRANCH} | cut -d '.' -f1-2 | tr -d 'v')

      - name: Create a github branch
        uses: peterjgrainger/action-create-branch@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: ${{ steps.get_branch.outputs.BRANCH }}

      - name: Commit changes to the minor branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: 'Update patch version'
          new_branch: ${{ steps.get_branch.outputs.BRANCH }}
          author_name: elasticcloudclients
          author_email: elasticcloudclients@elastic.co

  bump-minor-version:
    name: Bump main version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Bump main version
        run: make minor; git diff

      - name: Commit changes to main
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: 'Update minor version'
          new_branch: master
          author_name: elasticcloudclients
          author_email: elasticcloudclients@elastic.co
