name: Generate CHANGELOG
on:
  push:
  workflow_dispatch:
jobs:
  GenerateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - run: make changelog
      - name: Commit & Push changes
        run: |
          if [[ ! -z  $(git status --porcelain) ]]; then
            git config --local user.email elasticcloudclients@elastic.co
            git config --local user.name elasticcloudclients
            git add CHANGELOG.md
            git commit -m "Update CHANGELOG.md"
            git push
          fi
