name: Generate CHANGELOG and NOTICE
on:
  push:
    branches:
      - master
      - '[0-9].[0-9]+'
      - '[0-9].[0-9]+.[0-9]+'
    paths-ignore:
      - CHANGELOG.md
      - NOTICE
  workflow_dispatch:
jobs:
  GenerateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
        id: go

      - run: make docs-generate changelog vendor
      - name: Commit & Push changes
        run: |
          if [[ ! -z  $(git status --porcelain) ]]; then
            git config --local user.email elasticcloudclients@elastic.co
            git config --local user.name elasticcloudclients
            git add docs/ CHANGELOG.md NOTICE
            git commit -m "Update documentation, CHANGELOG.md, and NOTICE"
            git push
          fi
